name: Cypress testing

on:
  push:
    branches: [ feature/cypress-testing-workflow ]
jobs:
  test:
    name: test-dev
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Checkout envctl
        uses: actions/checkout@v2
        with:
          repository: hypha-dao/envctl
          ref: feature/full-environment
          path: envctl
      - run: pwd
      - run: echo $GITHUB_WORKSPACE
      - run: ls -latr $GITHUB_WORKSPACE
      - run: mkdir -p $GITHUB_WORKSPACE/envctl-data/repos
      - run: ls -latr
      - run: cp envctl-github-workflow.yaml envctl.yaml
        working-directory: ./envctl
      - run: go run . backend start
        working-directory: ./envctl